### ISSUE TITLE
Application crashes soon after invocation.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [techlore/Plexus-app#18]
### Screenshots/error messages (optional)
https://user-images.githubusercontent.com/42837531/222964339-ab926e72-ccff-4e1e-aa5a-a60af16cfa90.mp4

### Additional context (optional)
https://github.com/techlore/Plexus-app/releases/download/v1.0.0/Plexus_v1.0.0.apk acts identically.

**Comment by StellarSand** [comment]
Fixed with latest release.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/techlore/Plexus-app/issues/18#issuecomment-2194791376

@StellarSand, what changed?
