### ISSUE TITLE
What is the current status for adding apps?

### ISSUE THREAD

**Issue by dktzde** [techlore/Plexus-app#19]
I have already looked around a bit and learnt that you have just moved the data from CSV to josn. 
As I can't add any new ratings in the app yet, I wanted to ask what the current status is?
Am I right in assuming that I should currently refrain from adding reviews and wait until this is possible in the app?

Dktz

By the way: thanks for the website and the app!

**Comment by StellarSand** [comment]
> Am I right in assuming that I should currently refrain from adding reviews and wait until this is possible in the app?

Yes, It'll be possible directly from the app when v2.0.0 is released.

>  I wanted to ask what the current status is?

https://discuss.techlore.tech/t/is-plexus-dead/6201/2

**Comment by eylenburg** [comment]
> > Am I right in assuming that I should currently refrain from adding reviews and wait until this is possible in the app?
> 
> Yes, it'll be possible directly from the app when v2.0.0 is released.
> 
> > I wanted to ask what the current status is?
> 
> https://discuss.techlore.tech/t/is-plexus-dead/6201/2

That was almost three months ago, is there any news?

**Comment by StellarSand** [comment]
> That was almost three months ago, is there any news?

Unfortunately nothing new. Henry's been quite busy with other stuff. You can try asking in the forum though.

**Comment by StellarSand** [comment]
Use the latest version of the app to submit ratings. The website will be updated in due time.
