### ISSUE TITLE
422 when trying to verify email

### ISSUE THREAD

**Issue by shadowwwind** [techlore/Plexus-app#21]
### Description
When trying to verify my email I get an 422 error

### Steps to reproduce the behaviour
Click any app, click submit > enter email> click submit 

### Screenshots/error messages (optional)
If applicable, add screenshots or error messages to help explain the issue.

### Additional context (optional)
Any other relevant information or context that can help us understand the issue.

**Comment by StellarSand** [comment]
Looks like this is only an issue on the release build. Debug build works fine. My guess is something's been removed by proguard in release build. Will check.
