### ISSUE TITLE
Only allows submitions for microG

### ISSUE THREAD

**Issue by shadowwwind** [techlore/Plexus-app#22]
### Description
Iam using GrapheneOS without any form of google play services in that profile, I have google play in a separate profile. Trying to submit an review it eihter tells me the device needs to be de-googled or I need miroG. Or the submit menu opens but only shows options for microG.

I also accidentally created a broken rating for Element, which can be removed.

### Steps to reproduce the behavior
Go to any app
Click submit
After signup 
Tap the submit button

### Screenshots/error messages (optional)
If applicable, add screenshots or error messages to help explain the issue.

### Additional context (optional)
Any other relevant information or context that can help us understand the issue.

**Comment by StellarSand** [comment]
> Iam using GrapheneOS without any form of google play services in that profile, I have google play in a separate profile. Trying to submit an review it eihter tells me the device needs to be de-googled or I need miroG. 

The app detects if the device has Google Play services or microG installed. Submitting ratings is allowed only if the device is degoogled or has microG, which is the whole point of Plexus.<br>With the GrapheneOS sandboxed Google Play stuff I cannot help you or any other GrapheneOS user using this app (atleast for now).

> Or the submit menu opens but only shows options for microG.

I'm not sure how you're able to get into submit menu in the first place if the app is detecting Google Play services before submitting.

> I also accidentally created a broken rating for Element, which can be removed.

Done :heavy_check_mark:
