### ISSUE TITLE
Trying to open "my submissions crashes the app.

### ISSUE THREAD

**Issue by shadowwwind** [techlore/Plexus-app#23]
### Description
After signing in and creating a submission I tried to open the "my submissions" menu and the apo crashed

### Steps to reproduce the behaviour
Tap on "my submissions" button

### Screenshots/error messages (optional)
.

### Additional context (optional)
Any other relevant information or context that can help us understand the issue.

**Comment by StellarSand** [comment]
Very likely due to your GrapheneOS Google Play mess. Issue is not reproducible on my end. 
I'll wait for other non-GrapheneOS users to check if the same issue occurs for them.

**Comment by mtalexan** [comment]
I have CalyxOS with microG installed. Picking Contribute: Submit Rating -> pick an app -> Submit gives a pop up: "Device should be degoogled or have microG to submit a rating".
