### ISSUE TITLE
How to rate apps that only require Play Services on first startup

### ISSUE THREAD

**Issue by shadowwwind** [techlore/Plexus-app#25]
Some apps like Thorium only require Play Services on first startup and continue to work when play services get uninstalled afterwards. Should these get a broken or bronze rating?

**Comment by StellarSand** [comment]
You can mark such apps as `Broken` and mention in the `Notes` that they require Play Services on first startup and continue to work when play services get uninstalled afterwards.

**Comment by StellarSand** [comment]
Added support for line breaks. Changes will be reflected in the next release.
