### ISSUE TITLE
Rename (revert) "Submit ratings" category to "Installed".

### ISSUE THREAD

**Issue by RokeJulianLockhart** [techlore/Plexus-app#28]
### **Describe the feature to be implemented:**

Allow me to see in a list the ratings for currently installed applications.

### **Why do you need this feature?**

There's no *evident* way to filter installed applications, neither via the filtration menu:

> ![Screenshot_20240627-174206](https://github.com/techlore/Plexus-app/assets/42837531/8e8e9761-7b98-4cbc-8e28-482ebe2d3c77)

...nor the category list:

> ![Screenshot_20240627-174223](https://github.com/techlore/Plexus-app/assets/42837531/264e6dbc-05d6-44dd-9eb5-12bb5f35457b)

### **Additional context:** 

None of consequence.

**Comment by StellarSand** [comment]
Go to `Submit rating`. That will show you all your installed apps. You can filter from there.
<br>Initially it was named `Installed apps` instead of `Submit rating` but later it was changed so users know where to start submitting ratings from.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/techlore/Plexus-app/issues/28#issuecomment-2195224151

@StellarSand, that name is significantly less intuitive, and actually doesn't make much sense, since I can submit ratings via any of the views, for applications which aren't installed.

**Comment by StellarSand** [comment]
> that name is significantly less intuitive

Well this is definitely up for discussion now.

> I can submit ratings via any of the views, for applications which aren't installed.

You can submit ratings via any of the views (like `Plexus data`, `Favorites`): Yes :heavy_check_mark: 
You can submit ratings for apps which aren't installed: Nope. You have to install the app which you wanna submit the rating for.
In any case, as I mentioned, the name change is up for discussion.
