### ISSUE TITLE
Compare DB to installed

### ISSUE THREAD

**Issue by NobodyForNothing** [techlore/Plexus-app#29]
### Describe the feature to be implemented
A clear and concise description of the feature or change you would like to see in the app.

The app can get a list of all installed apps through the android api and match this data with the db. This way an overview of missing apps and apps that would stop working could be generated.

### Why do you need this feature?
Explain the motivation behind your request and how it would benefit the project or its users.

When downloading a compatibity app I don't want an overview of all apps that I have to manually check, I can do that online. I want a quick overview that matches my usages

**Comment by StellarSand** [comment]
Go to `Submit rating` from the bottom navigation view. Related #28
