### ISSUE TITLE
Add AospExtended in list of ROMs

### ISSUE THREAD

**Issue by marcdw1289** [techlore/Plexus-app#30]
### Describe the feature to be implemented
Include AospExtended in list of ROMs.

### Why do you need this feature?
AospExtended is on a couple of my devices (Oreo and A11).
Salecting 'Stock (device)' doesn't feel right. 😏
Guess I could go with something similar.

### Additional context (optional)
Provide any additional information, screenshots,
or examples that would help illustrate your feature request.

**Comment by StellarSand** [comment]
> Include AospExtended in list of ROMs.

I don't know how I missed that. Added now.

> Guess I could go with something similar.

I would instead recommend you to wait a couple days. A new release is planned with some bug fixes & improvements. This will also be included in it.
