### ISSUE TITLE
[Issue]: Update instructions for "Apps submission procedure" on the wiki's Help page

### ISSUE THREAD

**Issue by taivlam** [techlore/Plexus-app#34]
### Description

Step 1 in the "App submission procedure" of the on the wiki's [Help](https://github.com/techlore/Plexus-app/wiki/Help) page should be updated to reflect the current UI.

### Steps to reproduce the issue

1. Go to "App submission procedure" [section](https://github.com/techlore/Plexus-app/wiki/Help#apps-submission-procedure) of the on the wiki's [Help](https://github.com/techlore/Plexus-app/wiki/Help).
2. Read Step 1.

### Device

Both de-Googled & microG

### Error messages/logs

N/A

### Additional context

* Step 1 should be changed to reflect the current UI.  The UI direction flow is closer to this:
    * Hamburger menu > Contribute section > Tap "Submit rating"
* It seems that I can't edit the repo's wiki.

### Terms

- [X] This issue occurs on the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
- [X] This is not a duplicate of another issue.

**Comment by StellarSand** [comment]
I can tell you're not using the latest version. The wiki is already updated.
Please stop using the version from F-Droid. F-Droid CI is having unknown issues while building this app, even though it was confirmed reproducible while building locally more than 30 times and even on IzzyOnDroid. No one at F-Droid knows why or how to resolve this, so I cannot do anything to fix it as it's clearly not an issue on my end.

Use the **latest version** from either [GitHub](https://github.com/techlore/Plexus-app/releases/latest) or [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/tech.techlore.plexus).

To make your life easier, if you opt for GitHub you can use the [Obtainium app](https://github.com/ImranR98/Obtainium).
Alternatively, if you opt for IzzyOnDroid, do any of the following:
- Add the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid/repo?fingerprint=3BF0D6ABFEAE2F401707B6D966BE743BF0EEE49C2561B9BA39073711F628937A) in F-Droid app.
- Use [Droid-ify](https://github.com/Droid-ify/client) or [Neo Store](https://github.com/NeoApplications/Neo-Store) which already comes with the IzzyOnDroid repo enabled.

All builds are reproducible so you don't have to worry about signature conflicts & hence no need to uninstall the currently installed version before updating.

**Comment by taivlam** [comment]
Alright, thank you for the clarification.  I hadn't realized this and will use the latest version.
