### ISSUE TITLE
Crashes on DivestOS

### ISSUE THREAD

**Issue by zebede22** [techlore/Plexus-app#41]
divestos is a lineageos based ROM.
I have no microg.
It doesn't even open, just crashes

**Comment by zebede22** [comment]
Both from fdroid and github (obtanium)

**Comment by StellarSand** [comment]
I can see people are able to use the app on DivestOS just fine.

<img src="https://github.com/user-attachments/assets/c3be61b3-af94-44e3-b75f-8c7a71e29678" width=200> <img src="https://github.com/user-attachments/assets/421988df-f44c-4336-b198-8440bc3d4e6e" width=200> <img src="https://github.com/user-attachments/assets/a126d0dc-83e2-40a7-af34-0dff81822ddc" width=200>

<img src="https://github.com/user-attachments/assets/df6c060b-c283-4dfe-8fcd-a57883fe17bc" width=200> <img src="https://github.com/user-attachments/assets/ad326a27-f2e3-4a07-97ad-8be48f55378f" width=200> <img src="https://github.com/user-attachments/assets/0ad10274-5995-4a57-9d69-9f506d178bf3" width=200>

So if it is crashing for you, please upload the [crash logs](https://developer.android.com/studio/debug/bug-report).

Also from next time, please use the templates when reporting a new issue.
