### ISSUE TITLE
I currently have Microg installed, but also want to give rating to share my experience with apps when I was de-googled. How would I do that ?

### ISSUE THREAD

**Issue by Lurux** [techlore/Plexus-app#44]
### Description

I currently have Microg installed, but also want to give rating to share my experience with apps when I was de-googled. How would I do that ?

Is that possible at all ?Would uninstalling Microg work, or is that information tied to the email address anyways ?

### Terms

- [X] This feature is not present in the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
- [X] This is not a duplicate of another feature request.

**Comment by StellarSand** [comment]
Yes, just uninstall microG and relaunch the app. Your device will be detected as degoogled (assuming that there's no google services preinstalled).

**Comment by Lurux** [comment]
Ok, thanks for the input ! I'm wondering if the 1 review per account restriction will get in the way of doing that, will try your solution and keep you updated !

**Comment by StellarSand** [comment]
Yes setting up a work profile would also work.

> I'm wondering if the 1 review per account restriction will get in the way of doing that

There's no such restrictions. You can use the same email id in work profile or another device without any issues. The only restriction is 1 review per version of any app. Editing & deleting ratings will be implemented soon.
