### ISSUE TITLE
[Feature request]: Add option for app bar on top

### ISSUE THREAD

**Issue by christopherlam888** [techlore/Plexus-app#47]
### Description

Add an option in the settings to position the app bar at the top of the screen instead of at the bottom.

### Terms

- [X] This feature is not present in the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
- [X] This is not a duplicate of another feature request.

**Comment by spipau** [comment]
I agree as the navigation in the app is quite confusing and does not correspond with the Android design guidelines

**Comment by StellarSand** [comment]
The bottom navigation enhances accessibility, and implementing a top app bar would require additional maintenance to ensure both options work seamlessly with future updates, which I'm not looking forward to.

> the app does not correspond with the Android design guidelines

Regarding the design guidelines, they are indeed just that—guidelines & not rules, meant to be flexible. Developers have the freedom to adapt their apps and the components used as they see fit. :)
