### ISSUE TITLE
Non-free network service

### ISSUE THREAD

**Issue by julianfairfax** [techlore/Plexus-app#6]
What's the non-free network service anti-feature pertaining to?

**Comment by the-weird-aquarian** [comment]
The app connects to this repo to fetch the data from [here](https://github.com/techlore/Plexus-app/blob/main/Plexus.json). Since GitHub is owned by Microsoft, we had to include that anti-feature tag to abide by F-Droid's strict rules.

**Comment by julianfairfax** [comment]
> The app connects to this repo to fetch the data from [here](https://github.com/techlore/Plexus-app/blob/main/Plexus.json). Since GitHub is owned by Microsoft, we had to include that anti-feature tag to abide by F-Droid's strict rules.

Oh really? That's incredibly stupid. I mean I know GitHub is non-free and all but what you're actually hosting on it is.

**Comment by the-weird-aquarian** [comment]
One of the maintainers asked us to include it because of the reason stated above and we decided it's better to get the app included on F-Droid regardless of the anti-feature tag since this json format is temporary any way.
